### ISSUE TITLE
Custom CSS Preprocessor Solution

### ISSUE THREAD

**Issue by AlexBrown-appnovation** [18F/web-design-standards-drupal-d7#16]
My initial thought is to use SASS to write and output our custom CSS. 

The ideal setup would be a Gulp.js configuration that is watching all of the custom folders for changes in SASS, JavaScript, etc and output them accordingly. However, users should still be able to just add their own CSS files as they would normally if they are not in favour of using a task runner such as Gulp.js.

**Comment by fureigh** [comment]
+1 to [Sass](http://www.sass-lang.com), both because it's swell and because it's [what the U.S. Web Design Standards use](https://playbook.cio.gov/designstandards/getting-started/). Let's be sure to include the how-to of that (including how to watch files for changes) in #12.

Is there more to be addressed in this ticket? Do you want to write a Gulpfile or document how to do that (or how to use an alternate approach)?

**Comment by AlexBrown-appnovation** [comment]
I think it was more or less just to go get the go-ahead to use Gulp. I've got a Gulpfile already created and ready to go, although the documentation for it will need some adjusting. Would you want to write a separate issue for that or just track it here?

**Comment by fureigh** [comment]
Sounds good to me. Closing as covered in #20 and #21.
